[SingleStore]

# Your Management API key
api_token = your-management-api-key 

# Project settings
project_name = automated-project
edition = STANDARD

# Workspace Group settings
workspace_group_name = automated-wsg
region_id = your-helios-region-id 

# create a new, strong password here 
admin_password = your-secure-password 

# Allow connections from any IP address 
firewall_ranges = 0.0.0.0/0

# Workspace settings
workspace_name = automated-workspace
size = S-00

# Database settings
database_name = automated_db
